services:
  api01: # 01
    image: antongalaev/sunraysradio:latest
    hostname: api01
    expose:
      - "9001"
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: '1GB'

  api02: # 02
    image: antongalaev/sunraysradio:latest
    hostname: api02
    expose:
      - "9001"
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: '1GB'

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '1GB'

networks:
  default:
    driver: bridge
    name: hackathon
